# Generated by Django 3.0.2 on 2020-01-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biometrik',
            fields=[
                ('id_pegawai', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('id_pegawai', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('face_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
