# Generated by Django 4.2.20 on 2025-03-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipreti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='biometrik',
            table='vektor_pegawai',
        ),
    ]
