# Generated by Django 3.2.25 on 2025-03-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipreti', '0002_alter_biometrik_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometrik',
            name='id_pegawai',
        ),
        migrations.AlterField(
            model_name='biometrik',
            name='id_pegawai',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='biometrik',
            table='sipreti_biometrik',
        ),
    ]
