# Generated by Django 3.2.25 on 2025-03-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipreti', '0003_auto_20250329_1301'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='biometrik',
            table=None,
        ),
    ]
